#apiVersion: v1
#kind: Pod
#metadata:
#  name: flask-app
#  labels:
#    app: flask-app
#spec:
#  containers:
#  - name: flask-app
#    image: mtkg/trio-flask-app-img:latest
#    ports:
#    - containerPort: 5000
#    env:
#    - name: PASSWORD
#      value: root
#---
apiVersion: v1
kind: Service
metadata:
  name: flask-app
spec:
  selector:
    app: flask-pods
  ports: 
  - protocol: TCP
    port: 5000
    targetPort: 5000
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-deployment
  labels:
    app: flask-pods
spec:
  replicas: 5
  selector:
    matchLabels:
      app: flask-pods
  strategy:
    rollingUpdate:
      maxSurge: 20%
      maxUnavailable: 20%
  template:
    metadata:
      labels:
        app: flask-pods
    spec:
      containers:
      - name: flask-container
        image: mtkg/trio-flask-app-img:latest
        ports:
        - containerPort: 5000
        env:
        - name: PASSWORD
          value: root